version: '3.8'

services:
  bff-mobile:
    build: .
    image: martingrosek/bff-mobile:latest  # Dodajte to vrstico
    container_name: bff-mobile
    ports:
      - "4000:4000"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
